// Generated by scripts/generate-blur.ts
// Static tiny placeholders for next/image while remote product images load.

export const HERO_TILE_1_BLUR = "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACwAQCdASoIAAgABUB8JQBOgB6RB28AAP6Ye+lVEg9yUeEroAA=";
export const HERO_TILE_2_BLUR = "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAABwAQCdASoIAAgABUB8JQBOgBAwsAD492bMvRalOSGRkFk79YAAAA==";
export const HERO_TILE_3_BLUR = "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAQCdASoIAAgABUB8JZQAAlyo9QaAAP6tMinUQhiQF5AQMw0muyAA";
export const HERO_TILE_4_BLUR = "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoIAAgABUB8JYwCdADdDcWMAAD+awsYInF7lqpVkZbA3hCQFgAAAA==";
export const HERO_TILE_5_BLUR = "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoIAAgABUB8JQBOgB8xYS6XgAD+CzuNmZjpXpcWsQbEWQSxfAAAAA==";
export const PDP_FALLBACK_BLUR = "data:image/webp;base64,UklGRiwAAABXRUJQVlA4ICAAAACQAQCdASoIAAgABUB8JZwAApplHeAA+erlQrMGKYfoAA==";
