/* eslint-disable @typescript-eslint/no-require-imports */
const { mkdir, readFile, writeFile } = require("node:fs/promises");
const path = require("node:path");
const sharp = require("sharp");

type Asset = {
  name: string;
  src: string;
};

const DEFAULT_ASSETS: Asset[] = [
  {
    name: "HERO_TILE_1_BLUR",
    src: "https://cdn.dollupboutique.com/products/tr6/tr6-l-front.jpg",
  },
  {
    name: "HERO_TILE_2_BLUR",
    src: "https://cdn.dollupboutique.com/products/st703/st703-xs-front.jpg",
  },
  {
    name: "HERO_TILE_3_BLUR",
    src: "https://cdn.dollupboutique.com/products/st7/st7-m-front.jpg",
  },
  {
    name: "HERO_TILE_4_BLUR",
    src: "https://cdn.dollupboutique.com/products/st508/st508-xs-front.jpg",
  },
  {
    name: "HERO_TILE_5_BLUR",
    src: "https://cdn.dollupboutique.com/products/ss700/ss700-2xl-front.jpg",
  },
  {
    name: "PDP_FALLBACK_BLUR",
    src: "https://cdn.dollupboutique.com/products/ss24/ss24-xs-front.jpg",
  },
];

const OUT_FILE = path.join(process.cwd(), "src", "lib", "blur-data.ts");

async function main() {
  const assets = parseArgs(process.argv.slice(2));
  const constants = await Promise.all(assets.map(generateConstant));
  const source = [
    "// Generated by scripts/generate-blur.ts",
    "// Static tiny placeholders for next/image while remote product images load.",
    "",
    ...constants,
    "",
  ].join("\n");

  await mkdir(path.dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, source);
  for (const line of constants) {
    const [decl, value] = line.split(" = ");
    console.log(`${decl.replace("export const ", "")}: ${value.length - 2} chars`);
  }
}

function parseArgs(args: string[]): Asset[] {
  if (!args.length) return DEFAULT_ASSETS;

  return args.map((arg) => {
    const index = arg.indexOf("=");
    if (index <= 0 || index === arg.length - 1) {
      throw new Error(`Expected NAME=source, received: ${arg}`);
    }
    return {
      name: arg.slice(0, index),
      src: arg.slice(index + 1),
    };
  });
}

async function generateConstant(asset: Asset) {
  const input = await loadInput(asset.src);
  const blur = await sharp(input)
    .resize(8, 8, { fit: "cover" })
    .blur()
    .webp({ quality: 20, effort: 6 })
    .toBuffer();

  return `export const ${asset.name} = "data:image/webp;base64,${blur.toString("base64")}";`;
}

async function loadInput(src: string) {
  if (/^https?:\/\//.test(src)) {
    const response = await fetch(src);
    if (!response.ok) {
      throw new Error(`Failed to fetch ${src}: ${response.status} ${response.statusText}`);
    }
    return Buffer.from(await response.arrayBuffer());
  }

  const filePath = src.startsWith("/")
    ? path.join(process.cwd(), "public", src)
    : path.resolve(process.cwd(), src);
  return readFile(filePath);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
